# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jaka_zu20_controller
    - robotiq_gripper_controller  # 【新增】将夹爪控制器注册到 MoveIt 列表

  jaka_zu20_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  # 【新增】告诉 MoveIt 如何向夹爪发送轨迹指令
  robotiq_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robotiq_85_left_knuckle_joint

trajectory_execution:
  allowed_execution_duration_scaling: 1.5     # or 2.0, to allow 50-100% extra time
  allowed_goal_duration_margin: 2.0          # extra seconds to wait
  allowed_start_tolerance: 0.01  # Increase tolerance to reduce validation delay
  execution_duration_monitoring: false
  moveit_manage_controllers: true