# JAKA Zu20 Eye-in-Hand Calibration Result
# Method: ANDREFF | Precision: 0.42mm
handeye_parameters:
  # 变换关系定义
  parent_frame: "Link_06"
  child_frame: "camera_link" 
  
  translation:
    x: -0.03667   # -36.67 mm
    y: -0.12067   # -120.67 mm
    z: 0.00590    # 5.90 mm
    
  rotation:
    roll: 0.01585  
    pitch: -0.01271 
    yaw: -0.02323   